## 2.2

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
import pickle
import pandas


In [2]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

/home/lenovo/miniconda3/envs/ml/lib/python3.10/site-packages/sklearn/datasets/_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

## 2.3

In [3]:
# load data into dataframes
X = mnist["data"] #<class 'pandas.core.frame.DataFrame'>
y = mnist["target"].astype(np.uint8) #<class 'pandas.core.series.Series'>

# sort the dataframes by the target (0, 1, 2, ..., 9)
y.sort_values(inplace=True)
X.reindex(y.index)



pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
34999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56424     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56419     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
16705     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56415     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
13687     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
42651     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58914     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
13678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58529     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
34999      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56424      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56419      0.0  ...       0.0       0.0       0.0       0.0       0.0   
16705      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56415      0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
13687      0.0  ...       0.0       0.0       0.0       0.0       0.0   
42651      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58914      0.0  ...       0.0       0.0       0.0       0.0       0.0   
13678      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58529      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
34999       0.0       0.0       0.0       0.0       0.0  
56424       0.0       0.0       0.0       0.0       0.0  
56419       0.0       0.0       0.0       0.0       0.0  
16705       0.0       0.0       0.0       0.0       0.0  
56415       0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
13687       0.0       0.0       0.0       0.0       0.0  
42651       0.0       0.0       0.0       0.0       0.0  
58914       0.0       0.0       0.0       0.0       0.0  
13678       0.0       0.0       0.0       0.0       0.0  
58529       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

### Sorted data division
Divide the data into training and test sets, but leave the dataframes sorted by the target.
Resulting sets will not be the same size, they are useless.

In [4]:
# Not shuffled
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
X_train, X_test, y_train, y_test = X[:56000], X[56000:], y[:56000], y[56000:]

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(np.unique(y_train), np.unique(y_test))


(56000, 784) (56000,)
(14000, 784) (14000,)
[0 1 2 3 4 5 6 7] [7 8 9]


### Shuffled data division
Divide the data into training and test sets, but shuffle the data first.


In [5]:
# Shufled
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(np.unique(y_train), np.unique(y_test))


(56000, 784) (56000,)
(14000, 784) (14000,)
[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


## 2.4 Teach SGD to recognise digit '0'
sgd_clf = Stochastic Gradient Descent classifier

In [6]:
# reload data into dataframes
X = mnist["data"] #<class 'pandas.core.frame.DataFrame'>
y = mnist["target"].astype(np.uint8) #<class 'pandas.core.series.Series'>
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)

In [7]:
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)
print(np.unique(y_train_0))

[False  True]


In [8]:
# Learning process
sgd_clf_0 = SGDClassifier(n_jobs=-1)
sgd_clf_0.fit(X_train, y_train_0)

SGDClassifier(n_jobs=-1)

### [Points to collect here]
### Assessing accuracy of the model:


In [9]:
train_accuracy_0 = sgd_clf_0.score(X_train, y_train_0)
test_accuracy_0 = sgd_clf_0.score(X_test, y_test_0)
print("Train accuracy: ", train_accuracy_0, "\nTest accuracy: ", test_accuracy_0)

# save to pickle
with open('sgd_acc.pkl', 'wb') as f:
    pickle.dump([train_accuracy_0, test_accuracy_0], f)

Train accuracy:  0.9919642857142857 
Test accuracy:  0.9892142857142857


In [10]:
# from sklearn.metrics import accuracy_score
# train_accuracy_0 = accuracy_score(y_train_0, sgd_clf_0.predict(X_train))
# test_accuracy_0 = accuracy_score(y_test_0, sgd_clf_0.predict(X_test))
# print("Train accuracy: ", train_accuracy_0, "\nTest accuracy: ", test_accuracy_0)

`cross_val_score` function performs K-fold cross-validation on the given dataset, which means that it splits the dataset into K equal parts (or folds), trains the model K times, and each time uses a different fold as the validation set while the rest of the folds are used as the training set. Then, it returns an array of K scores, one for each validation set used.

In [11]:
# Using cross validation
from sklearn.model_selection import cross_val_score
score_0 = cross_val_score(sgd_clf_0, X_train, y_train_0,cv=3, scoring="accuracy", n_jobs=-1)
print("Cross validation score: ", score_0)

# save to pickle
with open('sgd_cva.pkl', 'wb') as f:
    pickle.dump(np.array(score_0), f)

Cross validation score:  [0.98532169 0.98725023 0.98462445]


___________________________________
### Additional metrics:  


`Confusion matrix`:  
[`not 0 as not 0`] [not 0 as 0]  
[0 as not 0]   [`0 as 0`]  
  
[true negative] [false positive  ]  
[false negative] [true positive]


In [12]:
# Using confusion matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
y_train_score0 = cross_val_score(sgd_clf_0, X_train, y_train_0, cv=3, n_jobs=-1)
y_predict_train0 = sgd_clf_0.predict(X_train)

In [13]:
print("Length of y_train_pred_0: ", y_train_score0)
print("Confusuion matrix:\n", confusion_matrix(y_train_0, y_predict_train0))

Length of y_train_pred_0:  [0.98794664 0.98912519 0.98526733]
Confusuion matrix:
 [[50310   183]
 [  267  5240]]


### Precyzja (precision) i czulosc (recall)

$$precision = \frac{true positive} {true positive + false postive}$$
what fraction of positive predictions is correct?
ile zidentkowanych jako dodatnie jest dodatnie  

$$ recall = \frac{true positive} {true positive + false negative}$$
what fraction of positive cases is correctly identified?
jaka cześć dodatnich została wykryta  

$$ F_1 = 2 \cdot \frac{precision \cdot recall} {precision + recall}$$
F1 score is the harmonic mean of precision and recall.

In [14]:
from sklearn.metrics import precision_score, recall_score, f1_score
print("precision score: ", precision_score(y_train_0, y_predict_train0), "\nrecall score: ", recall_score(y_train_0, y_predict_train0), "\nf1 score: ", f1_score(y_train_0, y_predict_train0))


precision score:  0.9662548404941914 
recall score:  0.9515162520428545 
f1 score:  0.958828911253431


## 2.5 Teach SGD to recognise all digits

In [15]:

sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y_train)

SGDClassifier()

In [16]:
# CONFUSION MATRIX
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_train_pred = sgd_clf.predict(X_train)
c_mx = confusion_matrix(y_train, y_train_pred)
print(c_mx)

with open('sgd_cmx.pkl', 'wb') as f:
    pickle.dump(c_mx, f)

[[5362    0   13   11    2   29   25    5   49   11]
 [   2 6111   48   16    4   26    4    5   74   15]
 [  18   23 5166  108   29   44   36   20  116   28]
 [  19    9  156 4882    9  362   10   28  113   90]
 [  21   14   26    8 4975   20   37    8   77  265]
 [  43   20   45  128   54 4456   52   15  149   77]
 [  28   12   51    6   21  128 5249    1   36    4]
 [  20   25  146   75   73   10    6 4889   32  559]
 [  30   50   96  165   28  388   48   19 4356  294]
 [  18   17    8   54  126   48    1   61   69 5185]]


In [17]:
y_test_pred = sgd_clf.predict(X_test)
cmx = confusion_matrix(y_test, y_test_pred)
print(cmx)

[[1347    0    5    4    3    8    9    0   12    8]
 [   0 1506   13    4    3   13    3    0   26    4]
 [   8   10 1271   27    8    8   10   17   38    5]
 [   5    5   40 1240    5   89    2    8   34   35]
 [   5    2   14    3 1223    4   11    2   17   92]
 [  12    4   15   38   16 1108   17    6   34   24]
 [  18    1   13    2    9   28 1260    0    8    1]
 [   8    9   27   19   23    6    0 1223    8  135]
 [   7   18   27   38   11  112   13    7 1054   64]
 [   7    4    7   23   37    9    0   20   17 1247]]
